version: '3'

services:
  app:
    container_name: blog
    restart: unless-stopped
    build: ./docker
    image: blog-dev
    volumes:
      - ${PWD}/www:/var/www
    ports:
      - 80:80
    networks:
      - blog
    env_file:
      - .env

  mysql:
    container_name: blog.mysql
    restart: unless-stopped
    image: mariadb
    networks: 
      - blog
    env_file:
      - .env

networks: 
  blog:
    driver: bridge